# Generated by Django 5.2.16 on 2026-07-12 06:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('game_name', models.CharField(max_length=100, verbose_name='게임명')),
                ('max_members', models.PositiveSmallIntegerField(default=5, help_text='2~12명, 기본 5명', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)], verbose_name='최대 인원')),
                ('status', models.CharField(choices=[('open', '모집중'), ('closed', '마감')], default='open', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL, verbose_name='방장')),
            ],
            options={
                'verbose_name': '방',
                'verbose_name_plural': '방',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room', verbose_name='방')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '방 멤버십',
                'verbose_name_plural': '방 멤버십',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='uniq_rooms_membership_room_user')],
            },
        ),
    ]
