# Generated by Django 5.2 on 2026-07-21

from django.db import migrations, models

from apps.accounts.profile_avatars import DEFAULT_PROFILE_AVATAR, PROFILE_AVATAR_IDS


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_avatar',
            field=models.CharField(
                choices=[(v, v) for v in PROFILE_AVATAR_IDS],
                default=DEFAULT_PROFILE_AVATAR,
                max_length=2,
                verbose_name='프로필 아바타',
            ),
        ),
    ]
